export const IS_FACE_RECOGNIZED = 'IS_FACE_RECOGNIZED'
export const IS_FACE_DETECTED = 'IS_FACE_DETECTED'
export const SENDING_BATCH_TO_SERVER = 'SENDING_BATCH_TO_SERVER'
export const SEND_RECOGNIZER_RESULT = 'SEND_RECOGNIZER_RESULT'
